### ISSUE TITLE
RSA interface metadata needs to be done

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#10]
In particular, we need to be able to get the RF_ROI_[MIN,MAX] values.

We should also test that they come out correctly, and that the external ref checks are done correctly.

**Comment by laroque** [comment]
Note, this becomes critical to #22 if we want to look at more than one ROI with the RSA-based DAQ without having to do it by hand.

**Comment by guiguem** [comment]
This has been implemented and merged in developed on July 15 2016. The 'RF_HF_MIXING', 'RF_ROI_MIN' and 'RF_HF_MAX' frequencies are saved into the metadata file of the RSA.
