### ISSUE TITLE
RSA interface should automate changing frequency

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#11]
In the [programmer's manual](https://drive.google.com/open?id=0B5MQV62BaCnbckVkaEVKODBRb28) page 2-1499 and 2-1500; it seems that `TRIGGER:MASK:NEW:AUTO` with well chosen arguments should draw a frequency mask for us in a consistent way. I haven't bothered to look it up but a similarly simple command should be available for setting the center frequency. An endpoint which changes the center frequency and automatically updates the mask would be excellent.

Obviously the operator should still be able (and even encouraged) to then manually review the result before taking data, but this would allow for things like automatic/overnight scanning of frequency ranges of interest.

**Comment by guiguem** [comment]
The creation of a new frequency mask can be asked in the execution script by giving the 'rsa_new_auto_mask' endpoint name and the 'TRACE3,--Xmargin--,--Ymargin--' with --Xmargin-- and --Ymargin-- that you want... This could be indeed automatized when the central/span frequency is changed. Should we try to do that? That will require some non trivial test/definition in the configuration files...

**Comment by guiguem** [comment]
@laroque The problem with such automoation is that we will need to provide a value for the frequency mask Y and X margin. This sounds very difficult...
