### ISSUE TITLE
PID sleep before check

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#112]
When the PID sets a new current, it immediately checks the current output and prints warnings if they don't match. When the change is large, it can take some time for the output to ramp to the new value. We should add a delay between these steps so that we can retain the relatively tight tolerance while also avoiding generating these warnings. It should be possible to do this in the same way that was done in the run scripting, or even better, using the newly more generic scheduler.

**Comment by wcpettus** [comment]
PID sleep implemented as of v1.8.4.  A more generic implementation for set and check, if desired should be defined in more detail in a separate issue.
