### ISSUE TITLE
Bad disk usage calculation

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#116]
The disk usage percentage reported to Slack doesn't match that calculated by `df` on a machine, presumably because `Used+Available != Size` and because diopsid only sends the size(?) and used.

Current reporting on zeppelin - 
diopsid
```
a8d0 17:11:16.008 INFO [main] ▶ Alert sent: [/data/warm] All: 938.26 GB Used: 719.31 GB
```
Slack
```
zeppelin:/data/warm -> Free space below threshold (24%); need to monitor!
```
df
```
/dev/sda1       983835532 754249988  179586544  81% /data/warm
```

**Comment by guiguem** [comment]
moving this to swarm
