### ISSUE TITLE
docker latest dragonfly version

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#127]
Possibly a problem with the Dockerfile in dragonfly or the build rules.

Creating a new docker image `FROM project8/dragonfly:latest` gives an outdated dragonfly version - `pip freeze` shows `dragonfly===v1.9.1-0-g9ef85d2`, and indeed the dragonfly code requires pulling to bring master up to date; further the dripline code is stuck at version `dripline===v0.0.0-` with the last commit being 954a659c84504c37e2317bfd2c6ead595cf9dd22.

Need to investigate further when we haven't just built off a bad tag push.

**Comment by guiguem** [comment]
the latest build of dragonfly is this one: https://hub.docker.com/r/project8/dragonfly/builds/bxxjgxn29fmbfx3chj9rhoi/
this is dragonfly v1.9.3

**Comment by wcpettus** [comment]
Still not sure why this happened, but it's a docker problem, not a dragonfly problem.  Rebuilding with `no-cache` option didn't resolve this, but the nuclear option does:
https://github.com/project8/insectarium#delete-all-containers
