### ISSUE TITLE
ethernet providers should support reconnecting automatically

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#16]
Note: this is a transfer of dripline issue #126

Details TBD but something like:
1) in send([*cmds]) have a try/catch on the actual send to socket.
2) If there is a broken pipe, call reconnect and resend that command
3) If reconnecting fails return a hardware communication error
4) If reconnecting works, continue as usual

**Comment by laroque** [comment]
An update to the details:

1) Provider should implement self._check_internal_status() which by default schedules a call to itself (in the same way as is done in loggers) and returns no errors (an empty list)
2) Providers for instrument would override the method and include a get() to a local endpoint which returns any error messages (it is important that if there are multiple errors present, it reads/clears them all). If the result of the get is not "no errors", the errors are recorded using a logger.critical() message (this results in it being sent to skype and any similar message distribution method we may later implement). The method then calls super() to ensure another check is scheduled after some set delay (10 minutes by default?) The errors found should be returned in a list form.
3) The self.send() method of Provider is modified to call self._check_internal_status() so that after sending a request, errors are checked and cleared. If any errors are returned, they can be included in the reply message to the request in the payload. Depending on the situation, they should potentially also result in a modified return code or return message in the Reply.

**Comment by laroque** [comment]
Ali is making good progress on the feature/ethernet-connectfix branch. Looking at 733aa27, we have a great start, but a few items to improve before we're ready to merge (1-3 should be very easy, 4-5 will take a little time/testing but shouldn't be bad either):

1) You broke the sending of commands out into its own function, that’s great, but you named it “func” which is not a good name. Please rename the method something unique and descriptive
2) You pass in the list `all_data` and let `func` fill it without a return statement. As written this will always work, however it is terrible practice in python (because of the way python internally deals with references/dereferences and when it does or doesn’t create new instances all having to do with which objects are or are not mutable). Instead, you should have “func” create its own local variable and then `return` it to wherever it was called. You can then do something like `all_data += func(cmds)` in the send function (be careful, += and [].append() do *not* behave the same way)
3) in the try/except/finally block, you should explicitly name the exception you are handling (whatever exception is raised when the socket connection is broken). Any other exceptions won’t be solved by that code block and so should be allowed to continue to raise.
4) The way you deal with the thread lock will appear to work, but it breaks the point of using the threading lock in the first place. The purpose of the lock is to prevent asynchronous code from trying to send data over the socket to the instrument, unless it is done responding to prior commands (otherwise, when you get data back there is no way to know if it is the rest of the reply to the 1st command or a reply to the 2nd command). You should not create a new lock at any point, but you will need to release the existing lock. You can work out your own solution here but the easiest thing is probably either to release the lock, call reconnect, then re-acquire the lock prior to retrying to call `func` (you could also have reconnect() internally release the lock if locked at the start and re-lock it at the end if it was locked, there are also other equally valid solutions.
5) What happens if reconnecting fails? I see you have a block that tests if all_data==[''] but I wouldn't actually expect that to happen, instead I would expect either reconnect() to raise an exception, or `func` to raise the same exception again. If this happens we want to raise our own exception telling the user that sent the request that we're unable to connect, probably code 201 dripline.core.exceptions.DriplineHardwareConnectionError() (to which you can pass a useful message, the same as any python Exception). We should also send a logger.critical() message in this case, so that a message gets posted to slack indicating that the instrument is unreachable and the operator knows to go take a look

**Comment by laroque** [comment]
A quick followup, there are three test-cases we should probably ensure work when we think we're ready to merge:

1) If the instrument is working normally and the connection is running, requests return correctly and the connection remains (ie reconnect not called) .... I'm basically certain this one already passes
2) If the instrument's network connection has reset, sending a request should still return correctly and to a user sending a request from dragonfly, this should look identical to the first case .... I believe that this currently works correctly also, but there are some best-practices fixes above and we should ensure that it still works.
3) If the instrument's network connection has dropped and has not reconnected, the service should do two things:
    1) send a reply to the request with an appropriate return code (201)
    2) make a logger.critical() call (which results in a post to slack alerting the operator if the service is on a system configured with proper slack tokens, and otherwise just prints a critical message to STDOUT)

**Comment by laroque** [comment]
Last I heard, the core of this was fixed, but there was some issue where responses were coming back to the wrong request. It wasn't well diagnosed but I wonder if it was possibly solved by Luis's changes for dealing with instruments echoing queries sent to them.

Also, a related feature might be nice:
If we haven't communicated with an instrument for some reasonably long amount of time (15 minutes by default?), we should query it, just to ensure it is still responding. This would hopefully mean that if something goes wrong, we'd find out immediately, rather than later when we try to talk to the device. (This seems especially helpful for figuring out why the issue occurred. If implemented, this could be combined with the result of [dripline issue 109](../../dripline/issues/109), which is probably the best thing to poll with other than a ping.

**Comment by guiguem** [comment]
Seems very related to #54...
