### ISSUE TITLE
bin/dragonfly uses unsafe yaml load

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#180]
This looks like a super-easy fix, just switch to safe_load?

Error on startup of dragonfly:
```
/home/project8/python_environments/latest_version/bin/dragonfly:216: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  conf_file = yaml.load(file_str)
```

**Comment by laroque** [comment]
seems like we should just try `safe_load`, have there been deprecation warnings about this?

**Comment by wcpettus** [comment]
I think the warning has been added in newer versions of PyYAML.  Somewhere between my test environment of 3.13 and the current of 5.1.

This will get picked up in the next release
