### ISSUE TITLE
New Operator Bot is Inactive after few days

### ISSUE THREAD

**Issue by buzinsky** [project8/dragonfly#181]
The operator bot has had some issues running over the weekend. I believe it was instantiated over the weekend by Walter (no operator). 2 things came up during the first week:

1.  On Monday, ~5pm EST, it lost who was operator, after successful running during the day. Walter resynced the google calendar, and this resolved the issue. Not believed to be a problem with the dragonfly code. Cause unknown

2. Today (tuesday), it did not seem like there was any successful instance of the operator bot working during this day. By this, I mean any pings to the bot (@ operator, !help, etc.) in correct channels, drew no response. In addition, the "status light" of the bot seemed to indicate it was away (potentially related to this: https://api.slack.com/docs/presence-and-status#bot_presence). When I ran a 2nd operator bot service, the new one worked correctly (and the bot had a "present" status). When the 2nd service stopped, the bot went offline, back to no responses. Restarting the original service completely made the bot respond correctly, and go back online (for now).

During my weekend tests, the bot did work on the Monday after the weekend. I did not check to Tuesday.

**Comment by wcpettus** [comment]
Just to clarify issue 1:
I checked the google calendar, where at_operator gets its information from, and the calendar event was missing (it got deleted?!?).  So when I resynced the calendar I was repopulating the events, then at_operator found the new event and started working as expected.  It never went unresponsive, it just saw that there was no active operator event.

For 2, we can check the calendar and see that the event persists, so that doesn't help.

**Comment by yadiw** [comment]
I did some search and it seems that the slack client disconnects silently is a common issue for bots using it. I added `auto_reconnect=True` in the code and thought it would solve the issue though. Was there any exception saying something like "maximum reconnect reached", or it simply lose connection silently?

**Comment by wcpettus** [comment]
Looking at the logfile reveals why it stopped responding, but not how it reached this state:
```
2019-03-26T00:04:25[INFO    ] dragonfly.implementations.at_operator(438) -> Updated the Google Calendar event list.
2019-03-26T00:04:25[INFO    ] dragonfly.implementations.at_operator(216) -> Constructed dictionaries for full names, Slack usern            ames and ids.
2019-03-26T00:04:25[INFO    ] dragonfly.implementations.at_operator(447) -> Updated Slack users information.
2019-03-26T00:04:25[INFO    ] dragonfly.implementations.at_operator(451) -> Updated the operator information.
2019-03-26T00:04:25[INFO    ] dragonfly.implementations.at_operator(453) -> Next update will occur at 2019-03-26 00:05:25.695077            
2019-03-26T00:05:26[INFO    ] dragonfly.implementations.at_operator(438) -> Updated the Google Calendar event list.
2019-03-26T11:54:47[DEBUG   ] dripline.core.service(450) -> Stopping
2019-03-26T11:54:47[DEBUG   ] dripline.core.service(373) -> Sending a Basic.Cancel RPC command to RabbitMQ
```

Apparently it froze somewhere in this loop after getting the calendar event list

**Comment by yadiw** [comment]
So it stopped when trying to get data from Slack. But by looking at the logfile I am not sure if the maximum reconnect exception was raised properly or not. 

And just a side note - it seems like the regular update interval is 1 minute. Wouldn't it be a little bit too frequent?

**Comment by wcpettus** [comment]
If the exception was raised properly, shouldn't that crash the at_operator service?  I don't see a try/except that I would expect to catch and recover.

This update interval is how often the script checks the GCal for events and Slack for users?  I think it's a tradeoff since the old version did every 5 sec.

**Comment by buzinsky** [comment]
The 1 minute interval was chosen as I understood that to mean when the shifts changes at 9:00 am EST Pacific time, it takes ~1 minute for the bot to recognize the new operator. We don't want to wait several hours for the new operator to be recognized. Its true, during the rest of the week, we certainly don't need the high frequency. Is this correct interpretation of code?

**Comment by yadiw** [comment]
1. that exception is supposed to be raised when it tried to reconnect for 5 or 6 times I believe? Seeing that would help me make sure that at least `auto_reconnect` is doing something useful - but the service still stops anyway. So maybe I will try to add something to manually do the reconnection.

2. the "regular" update - the one that uses the interval - and the update occurs when the shift changes, these two updates are supposed to be handled independently (see line 430 and 454 - I also notice a typo :( ) The regular one is supposed to do the update in case you add something new but not urgent to the calendar, or a member's information in Slack has been changed, etc. And the other one is supposed to handle the shift switching - it will be triggered when the current shift ends, or next shift starts. In this way it can avoid retrieving same data from calendar and slack too frequently.

**Comment by wcpettus** [comment]
this should be fixed now in v1.15.2

**Comment by buzinsky** [comment]
This issue seems to have come up again here on Fri. Apr 19/19 11:20 am PT. It seems like the service was started the previous thurs apr. 11, at ~ 3pm PT, during the upgrade.

**Comment by wcpettus** [comment]
this is maybe different - it seemed to crash on a request to @operator
```
2019-04-19T09:41:53[INFO    ] dragonfly.implementations.at_operator(480) -> @operator is called in the channel [operations]! Loo            king for the operator...
2019-04-19T09:41:53[DEBUG   ] dragonfly.implementations.at_operator(263) -> Found the current operator!
2019-04-19T10:20:51[INFO    ] dragonfly.implementations.at_operator(480) -> @operator is called in the channel [operations]! Loo            king for the operator...
2019-04-19T10:20:51[DEBUG   ] dragonfly.implementations.at_operator(263) -> Found the current operator!
2019-04-19T10:20:51[INFO    ] dragonfly.implementations.at_operator(486) -> Being terminated...
2019-04-19T10:20:51[INFO    ] dragonfly.implementations.subprocess_mixin(71) -> end of work/sleep loop
2019-04-19T10:24:55[DEBUG   ] dripline.core.service(450) -> Stopping
```

If we include a generic `except Exception as err` block before the finally, we should be able to print out what the raised exception that breaks our try loop is, and debug it.  I'm not sure if this will be a recurring issue or not.

**Comment by wcpettus** [comment]
debug included in last dragonfly release, if this shows up again it's not the same as the original issue and can be addressed separately
