### ISSUE TITLE
dungbeetle handling of .nfs files

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#206]
DIRAC transfers are now stranding .nfs files on /data/warm whenever there are issues.  These files prevent the directories from being removed from dungbeetle, generate warning messages, and require manual intervention.

Dungbeetle could be modified to check for the existence of .nfs files blocking the cleanup, and purging them.  Maybe we still want a warning message when it does cleanup this bad state (like how psyllid gives a warning when the liveness probe fails) so we can track it, but it won't be a recurring warning for the same known issue, only a one-off.

Probably the .nfs should only be removed if it has been stagnant for some time period?

**Comment by buzinsky** [comment]
I do want to mention that you definitely do want to wait for some time period before removing the nfs files: I have seen them produced during normal data transfers, its just that they get cleaned up (by the transfer agent?) automatically when everything is working

**Comment by buzinsky** [comment]
This was resolved in #207 , right?

**Comment by wcpettus** [comment]
Yes, thanks for catching that.  We get a single warning when removing these stagnant files.
