### ISSUE TITLE
dragonfly tutorial edit: running server with dragonfly 

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#24]
In the tutorial found at: http://www.project8.org/dragonfly/tutorials/kv_store.html. Under the section entitled "Starting the Key-Value service", the following command text must be changed from:

dragonfly serve -c examples/kv_store_tutorial.yaml -v

to:

dragonfly serve -v -c examples/kv_store_tutorial.yaml

so that it runs properly.

**Comment by wcpettus** [comment]
I can't reproduce this issue.  Shouldn't these flags be order-agnostic?

**Comment by guiguem** [comment]
They should indeed.
