### ISSUE TITLE
more complete slack integration

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#28]
The slack message handler is useful for sending critical messages, but should handle more cases. In particular. It is common for a service to have an error and return a message which is sometimes lost if there are several services between the user and the processes that actually does some action (user runs execution script, which starts a run using the run interface, which asks the run_id table interface for a run_id for example). having those error messages also in slack might help in cases where they don't get all the way back.

**Comment by wcpettus** [comment]
Abandoning this issue. #56 is the path forward.
