### ISSUE TITLE
Delay in Glengyle Responce

### ISSUE THREAD

**Issue by AliAshtariEsfahani** [project8/dragonfly#32]
Glengyle is showing some weird behaviors. When I disconnect the ethernet plugin it will response to one more request. 
I checked bowmore and glenlivet if they have the same problem. They were working just fine.
So first of all we should check other instruments. 
Then we should see what is going wrong with the glengyle.

**Comment by wcpettus** [comment]
Resolved for some time now.
Some instruments expect to give a response when a socket is opened, which if ignored can cause the responses to get out of sync (it is always giving the response to the previous command).  Including a cmd_at_reconnect in the settings allows these responses to be checked.
