### ISSUE TITLE
ethernet provider has issues in connecting to wolfburn and lagavulin

### ISSUE THREAD

**Issue by AliAshtariEsfahani** [project8/dragonfly#34]
As we try to connect to these prologix boxes we receive the "Cannot connect!" message from the ethernet provide.

**Comment by AliAshtariEsfahani** [comment]
It turns out that wolfburn is actually running even if it is sending the 'Cannot Connect!' message. We can run bowmore config file and work with it.
I will look into ethernet provider and fix the false alarm.

**Comment by wcpettus** [comment]
The prologix boxes are fully functioning with EthernetProvider.  Connection errors are caught and handled (via reconnect) since at least v1.1.0 (although I believe this specific problem was resolved earlier).
