### ISSUE TITLE
muxer service (muxer_glenlivet.yaml) crashing while logging values when it runs on personal computer

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#39]
For testing purposes, I have been running the muxer service from my personal computer (as opposed to on Claude). Issue: the service starts up, endpoints are created, channels are configured (without error), setup-calls loop starts - which includes a call to log values, it loops once through the endpoints and sends these values to the alert exchange (which are then logged by sc database service), then the service crashes on line 435 of dripline.core.service and it send a `supposed to do an emit` error message.

A few observations: 1) If only 5 endpoints are included, the service runs smoothly. If any more are included it crashes. 2) The source exception is being raised by pika (the AMQP python implementation) stating `ProbableAccessDeniedError` - pointing to broker connectivity issues. 3) The full service seems to have a much faster start-up time when run on Claude and it runs smoothly there as well (with full config file); same versions of dragonfly/dripline are being used here as in my computer.

Possible fix?: Set a delay time in the set-up calls in dripline.core.service (line 432) there will give the service time to be fully initialized before trying to run the calls.

**Comment by guiguem** [comment]
@les67 What is the status of this problem?
Is this related to the problem Noah/Gray were having recently in the database?

**Comment by les67** [comment]
@guiguem Further testing was halted as the service was successful from Claude and data taking started in the beginning of the summer. I believe that this is not the same problem with the database as discussed by Noah and Gray.  I could try to re-address the issue when there is no data taking; I would have to coordinate with the operator. But this seems of low priority now since we've ran the muxer service without crashing since then, again, from Claude.

**Comment by les67** [comment]
Irrelevant to current operations. Given that the muxer service has not reproduced this error, running under supervisor on Claude, this issue is being closed.
