### ISSUE TITLE
sc database service crashing with "list index out of range" - warning instead of crash needed 

### ISSUE THREAD

**Issue by les67** [project8/dragonfly#41]
When a sensor log message is received, the service attempts to log the value. If this fails, the service crashes. This crash is occurring every time an endpoint hasn't been properly added to the database, yet it is set to be logged in its respective configuration file. A warning here is more appropriate than a crash. The exception should be generated and caught and a warning generated which the service should send to Slack notifications to display.  

postgres_interface.py - starting on line 130

**Comment by guiguem** [comment]
Same as #30
