### ISSUE TITLE
Slow control time series file

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#44]
In order to limit the access to the slow control database server when doing offline analysis, we can make a file which contains the time series of the detector instruments (such as temperatures, trap coil configuration, others).
This will also allow to make cuts if necessary later without requiring an access to the sc database

**Comment by laroque** [comment]
The cleanest solution to this would be a `dripline.Gogol` which the daq_interface could trigger before starting a run and then stop once the run ends. It would collect all broadcasted sensor values during the run, preventing us from needing to do any queries of the database after the fact and keeping things moving along during the dataflow.

The concerns are:
1) this datafile needs a format (hdf5? json? something else?)
2) the output file needs to make it into the dataflow path; does it get sent to hornet the same as the metadata file? could hornet be extended to also serve this purpose?
3) (possibly related to 2), how do we ensure that this file gets added to the data before hornet cleans up the hot directory?

**Comment by nsoblath** [comment]
Regarding Ben's concerns:

1. I suggest hdf5 to match our data file format and overall reduce our spread of dependencies.
1. Extending hornet to deal with this file is trivial.
1. Empty directories are cleaned up by dungbeetle.  They have to be empty for some specified period of time.  Currently that time is set to be 2 hours, so this won't be a problem.

**Comment by guiguem** [comment]
#67
