### ISSUE TITLE
console handler output direction

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#48]
As currently implemented, the console handler sends everything to stderr (the default for python's internal logging.StreamHandler). We could instead send some messages to stdout, separating status from error messages, allowing easier division in log files. Whatever is done should be standardized across dripline-based tools.

@nsoblath could you comment on what is done in mantis, psyllid, hornet, etc.? In particular
- If it is split, are where do "warning" messages get put?
- Is it actually a split, or do errors go to both (so you can easily see where they interleave) while debug messages only go to out so that errors are easier to find?
- Conventions I've missed that we should standardize?

**Comment by nsoblath** [comment]
## C++
Implementations are in scarab::logger and nymph::KTLogger

As currently implemented, `prog`\*, `info`, `debug`, and `trace`** go to stdout, and `warn`, `error`, and `fatal`** go to stderr.

## Go
Implementations are in swarm::logging, which uses `github.com/op/go-logging`.

From the documentation I wasn't able to determine which output stream is used for the various levels of logging.  Presumably it would be pretty simple to test, though.

## Conventions
Consistently sending messages to the various output streams seems like a good idea.  I'm not sure how to do it for the Go code, but that's probably less critical than for the analysis and controls.

I think we're fairly consistent in what gets prepended to each message: timestamp, code location, and message type.  As long as we have that information, I think it's probably fine.  We don't really need to be 100% consistent in how that's formatted.

----

\* `prog` is a message type that currently only exists in Nymph/Katydid and is intended to allow production code to run faster by disabling almost all normal output, and only showing minimal "progress" messages.  It will eventually be migrated to Scarab.

\*\* AFAIK these are never used in the current codebase.

**Comment by wcpettus** [comment]
Regarding go, it looks like everything goes to stdout.  Checking the supervisor logs, I can see INFO, DEBU, NOTI, and ERRO (not sure what else is programmed, but nothing has ended up in stderr)

**Comment by wcpettus** [comment]
I took a stab at this for python, commit here:
https://github.com/project8/dragonfly/blob/8d23d3a65c2132ef946dcf0d28e38815367042ec/bin/dragonfly

The fix can be implemented entirely in bin/dragonfly in the configuration of the logging.StreamHandler:
- level 1 fix: assign the StreamHandler to sys.stdout (default is stderr), this dumps everything in stdout instead
- level 2 fix (current): create a new StreamHandler for stderr with fixed level of >= WARN

The irritating bit about this is the terminal will get double-warnings (both stdout and stderr), so I think we only want the stderr stream created for dragonfly.subcommands.open_spimescape_portal.Serve objects?

**Comment by wcpettus** [comment]
The last irritating bit is now resolved - stderr StreamHandler is only added `if isinstance(these_args.func, dragonfly.subcommands.open_spimescape_portal.Serve)`, so it is suppressed for all get/set/cmd/execute/monitor/...

**Comment by nsoblath** [comment]
I can see where in the go code the setting is made to use stdout.  In principle it should be possible to direct things < WARN to stdout and >= WARN to stderr.  What's the timescale on which we want this done?

**Comment by wcpettus** [comment]
Until firefly is equipped to review standard error/output logfiles, I think this remains a very low priority.  We can also wait and see how we like the new dragonfly log splitting before imposing this on golang.

Closing this issue for now, since it has been addressed.  Worth thinking about uniformity and opening issues across languages when we know what we want.
