### ISSUE TITLE
Integrate the esr measurement as a run

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#49]
In the run_scripting, the esr measurement are currently done by executing a cmd in the multi run or in the action: do. These measurements should be done at the same level as a electron measurement run. Also one should have the possibility to select between doing or not doing the initial configuration of the esr instruments before the measurement: this will then allow oneself to take esr data for a systematic study of one of the parameters.
This will require:
- slight modifications into the esr class, such as the possibility not to execute the "configure_instruments" method in the "run_scan" method.
- the possibility of selecting which esr coils measurements to take (might require some modifications in the way the data are saved/fitted) in the "run_scan" method.
- a "action_esr_measurement" method in the run_scripting, which start a data taking (aka send a cmd(esr_interface.run_scan).
- a "run_esr" key might be added in the execution script. If present, the esr measurement will be done prior of the electron measurement. If not, the electron measurement will happen right after the last operation (set or cmd). 
- if no "run" is present in the execution script, no electron data are taken (independently of the presence of a esr measurement).

**Comment by wcpettus** [comment]
All points satisfied in dragonfly release/v1.1.7 (developed in feature/run_scripting).
