### ISSUE TITLE
Run_scripting values parsing update

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#51]
The evaluator capabilities are not used at their full potential. One should for example be able to give a: '[[1]*6,[2]*6]' which should be interpreted as a list of list and then rewrite as a simple list. This will be very useful when taking data using the RSA for multiple magnetic depth, for example.

**Comment by guiguem** [comment]
done, if a string such as '[[6]*2,[8]*3]' is given as a value in a set, this will be interpreted as a list [6,6,8,8,8]. for the nth run in the multi_run, the nth element of this list will be used.

**Comment by laroque** [comment]
Mathieu, I'm sorry I didn't see this issue before, that syntax is probably not desirable. Python already has support for this, it looks like: `[[6]*2,[8]*3]`. An asteval should already be able to deal with such syntax (or any other valid python, like list(range(3)) or whatever) and we should stick to that.

**Comment by guiguem** [comment]
oh ok, the main problem was to transform lists of lists into list to be used in the run_Scripting
I guess something similar can be done then...

**Comment by laroque** [comment]
sorry, `[6]*2 + [8]*3` should evaluate to `[6,6,8,8,8]`

**Comment by guiguem** [comment]
so it works!
