### ISSUE TITLE
make root dependency optional

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#53]
ROOT is only used in the ESR system, it should be an optional dependency with a protected import and a useful exception raised if one tries to initialize the class with the dependency.

There are probably other dependencies that have been added and treated similarly, would be worth going through and treating all of them similarly. The requirements file may also need updating and it may be useful to have a minimal one and several, one for each set of optional dependencies.

**Comment by wcpettus** [comment]
I noticed in @les67's new SQLSnapshot feature branch we have a similar dependency issue with a slightly different method of handling the import.  I thought this might be a good opportunity to consider the best practice.

ESR - 
```python
try:
    from ROOT import gROOT, ...
except ImportError:
    pass
```
and then in init:
```python
    def __init__(self,...):
        if not 'gROOT' in globals():
            raise ImportError('PyROOT not found, required for ESR_Measurement class')
```

SQLSnapshot - 
```python
try:
    import sqlalchemy
    __all__.append('SQLSnapshot')
except ImportError:
    pass
```

Both methods will allow dragonfly to run on machines without sqlalchemy/ROOT.  If you call ESR on such a machine it will crash with an ImportError and the specified error message, whereas if you call SQLSnapshot on such a machine it will successfully start(? not entirely sure).

(Apologies for dragging code-under-development into an issues discussion)

**Comment by laroque** [comment]
I'm open to suggestions but like the idea that if I try to run something with a missing dependency, I'd be told what that missing dependency is rather than just getting an import error on the dragonfly class. There is probably a cleaner solution than either of these cases that still achieves that but I'm not sure what it is.

**Comment by les67** [comment]
@wcpettus, your method is clearer. I have updated the import statement in SQLSnapshot to supply information as to the source of the error.

**Comment by laroque** [comment]
@les67 @wcpettus I think this is done (and probably has been for some time). Would you both confirm so we can close this issue?

**Comment by wcpettus** [comment]
Confirmed.  The "ESR" method from my above reply has been adopted and can be used as a template for future dependencies.  See full implementation in the current version of esr_measurement.py:
https://github.com/project8/dragonfly/blob/32847df02b8b856337575fb392f5ebb6b352cd39/dragonfly/implementations/esr_measurement.py
or sql_snapshot.py:
https://github.com/project8/dragonfly/blob/7329137172c253816ce1ff7cb267bc9ccec1f009/dragonfly/implementations/sql_snapshot.py
(both of those are the current master version)
