### ISSUE TITLE
Unified use of Interface/Provider/Portal

### ISSUE THREAD

**Issue by wcpettus** [project8/dragonfly#55]
Services can communicate via provider.send, portal.send_request, or interface.get/set/cmd.  The communications methods should be codified.

Currently usage:
- self.provider.send:
  spime.py (SCPI classes), lockin_provider.py, prologix_provider.py
- self.portal.send_request:
  daq_run_interface.py, esr_measurement.py, multido.py, multiset.py, repeater_provider.py
- pid_loop.py (uses self.send_request since it inherits directly from Service through Gogol)
- self.interface.get/set/cmd:
  run_scripting.py

Since interface was created to bypass the clunky formatting of send_request (and creating a request_message), portal usage should be deprecated at this level in favor of interface.

Related is dripline issue #161 (https://github.com/project8/dripline/issues/161), which affects inheritance of broker knowledge for the interface classes.

**Comment by laroque** [comment]
The major caveat is that the interface was not intend to coexist with other service-derived objects. That's not an issue in run scripting which is client side, but is for anything involving the serve subcommand. While it may work to have both for now, it will make things much messier to maintain. Instead, I recommend merging Gogol and Spimescape and adding the useful interface methods to Provider. The preferred usage would then be `self.portal.set()` and the like. We could also rename self.portal to self.provider since that makes way more sense.

**Comment by wcpettus** [comment]
We can't rename self.portal to self.provider carelessly since self.provider already exists - both are declared in dripline/endpoint.py as None.  And conveniently spimescape and provider both have add_endpoint methods that define self.portal and self.provider (respectively).

There should probably be a separate issue in dripline where @laroque decides how dripline functions, and then this issue should reflect that proper methodology.

**Comment by laroque** [comment]
On dripline and dragonfly I've pushed branches named refactor/services; the dripline version is probably close to okay, the dragonfly I'm less confident about but dont' have a good way to test while everything is running.

The recommended resolution looks like this thus far:
1) endpoint's `self.portal` has been renamed `self.service`, this is "cosmetic" but makes it more clear when you are interacting with the `Service` (object responsible for direct AMQP interactions) vs the `Provider` (translation layer for endpoints which may or may not happen to be the same object as the Service depending on the configuration being used)
2) the base Provider class now implements utility methods for get, set, and cmd. The are similar but not identical to those from Interface. These create Message objects, send the message, and return the payload (not the ReplyMessage). The current behavior is that if there is a non-zero return code the exception gets raised (with any available payload in the exception's result field). Services using these methods are encouraged to do so in try/except blocks if there is desired logic in the case of non-success.
3) For now, the `Interface` class remains, it is for use in subcommands that run client side, not in association with another instance of `Service`. I'll continue to think about if there a more sensible form for it to take.
4) The boundary between `Gogol` and `Spimescape` remains poorly defined and they should merge

This is further described in dripline issue 162

**Comment by wcpettus** [comment]
I'm unclear on the proper implementation of (2).  The daq_run_interface.py in refactor/services uses self.provider.get/set/cmd methods, but these aren't actually available to them.

provider.add_endpoint (which makes self.provider a valid thing) is only done in open_spimescape_portal to daughter endpoints of a provider.  The actual provider only gets self.portal (now self.service) assigned.  When trying to access these provider.get/set/cmd methods, dripline will raise an error:
2016-08-28T16:44:08[Level 25] dragonfly.subcommands.dripline_agent(85) -> return message: 'NoneType' object has no attribute 'get'
since self.provider is still None after its declaration in Endpoint.__init__

So it seems either we need to modify open_spimescape_portal.py to change how add_endpoint is done, or change spimescape add_endpoint to define self.provider or something.  I don't know if this belongs as a dragonfly or dripline issue.

**Comment by laroque** [comment]
hm... looks like a bit of both

open_spimescape_portal line 102 is supposed to be calling Provider.add_endpoint for each child, which should be setting self.provider. Line 105 is meant to call Service.add_endpoint for those cases where the provider and service are not the same.

looks like in `Spimesape`, the add_endpoint() method needs to also call `Provider.add_endpoint(self, endpoint)... (ie Spimescape inherits from Provider and overrides the Provider.add_endpoint method, it can explicitly call the parent method to ensure that the logic from both happens without duplicating the code). We probably also want to change the order so that lines 103-105 come before 101-102 (that way service.add_endpoint will set both self.provider and self.service to  point at the service (which should work), then Provider.add_endpoint should override the value of self.provider only to point to itself, that way a provider can modify those methods for its endpoint if needed.

**Comment by wcpettus** [comment]
Taking the rsa as an example, rsa/Spimescape is the service module of line 56, rsa_interface/RSAAcquisitionInterface is the provider module of line 60.  So in the current version rsa_interface only has service(Spimescape).add_endpoint called on it, which explains why it is missing the self.provider declaration.  Lines 101-105 are only called for third-level modules, with 103-105 being specifically where the second-level module is a Provider.

**Comment by wcpettus** [comment]
Starting with release v1.1.10, there is a way forward on this issue, and the suggestions here are ready in the released code:
- self.provider now has get/set/cmd methods implemented that can be used by all modules (since the top-level Spimescape module has them)
- use of self.portal.send_request should be deprecated in favor of these cleaner self.provider.get/set/cmd methods
- self.portal is renamed to self.service to simplify naming conventions
- Gogol now inherits from Spimescape

We still need to go through the dragonfly implementations and unify their communication, but the tools are all there.

The implementation of get/set/cmd in provider.py is hopefully general enough to be useful, but this should be commented on if insufficient:
- if successful, will return reply.payload
- if unsuccessful (error code), will return the appropriate exception as `raise exception_map[reply.retcode](reply.return_msg, result=reply.payload)`, so that try/except loop in the higher-level code can still catch and provide a more finely-tuned response

**Comment by wcpettus** [comment]
We have defined a new standard in this issue, which has been applied throughout dragonfly:
- to access another the endpoints of another dragonfly service, use self.provider.get/set/cmd
- use of self.portal.send_request is deprecated, to access those endpoints, see above
- use of self.portal is deprecated (naming convention), if _absolutely necessary_ use self.service, but ask because there is probably a better way
- use of self.interface is limited to run_scripting, which doesn't function as a normal service
- use of self.provider.send is unchanged, as it is the mechanism for spimes (or other endpoints) to communicate with their provider's send method

There is always an exception to the rules:
- repeater_provider uses self.service.send_request to communicate with the send method of a different provider.  Since this is a non-generic use case there is no self.provider.send to OP_SEND to another provider.
