### ISSUE TITLE
pid_loop initialization

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#65]
The pid_loop does not try to turn the output of the cell heater on before pid_lopping on it.
As a consequence, the service can run but does not regulate things.
One has then to be careful since if someone turns this on after a long time of non regulation, the current output would be equal to the current limit of the pid loop (currently 2Amps -- ok, this is not a big deal actually).
In general there should be some initialization to be performed...

**Comment by guiguem** [comment]
If no initialization should be performed, then pid loop should detect if the output is on or off, and throw an error if the thing is not well configured.

**Comment by laroque** [comment]
I'd recommend a more generic solution. This doesn't solve the problem of someone turning the output off later. Maybe there's some cause for concern and someone disables the output of all power supplies for whatever reason.

Instead, I suggest the PID loop check the current output after setting a current limit. If the output is not within some tolerance of the desired output then an error can be raised. That way we get the check from the start but also at any point while operating. Further, this would catch more problems than just a disabled output (such as a cable being disconnected).

**Comment by guiguem** [comment]
ok I see.
This set and check should be simpler than the multiDo one, so I will try to implement it

**Comment by guiguem** [comment]
This has been implemented in release/v1.2.0

**Comment by guiguem** [comment]
We have implemented a solution for generically catching errors.
We might still want to have an initialization of the power supply when starting the services and/or a set of the output status and current limit if there is a mismatch and the current value is zero.
The logic is easy to implement.

**Comment by wcpettus** [comment]
The pid_loop will now check if the output_status is on both when the service starts (will crash if it isn't), and if the set_and_check fails.
