### ISSUE TITLE
disk use and/or data rate monitor

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#72]
This is a placeholder issue which we will hopefully clarify on the upcoming issues call. Sometimes there are problems with dataflow and a backup can occur. We have a bit of leeway as the warm disk fills, but eventually data taking must stop (see #71 ). We need to define what condition or conditions trigger this (disk_usage > some_limit? data_transfer_rate < some_limit? something else?)

The simplest incarnation would be a service which monitors hot and/or warm disk usage (we could even log it, plots of this over the course of extended data taking could be useful for estimating how much hot/warm storage we'll want in the future). In the event that a log value exceeds some limit, a set_condition could be sent.

We should also consider how this relates to the "advanced watchdog"... For simple monitoring, it seems nicer to let each endpoint monitor itself (that way you could do things like `dragonfly set an_endpoint.max_value_alert_limit new_value` to change the trip point), though the advanced watchdog probably remains useful for more complex logic if needed (also as a place to more easily/quickly implement the behavior that may eventually migrate into a generic endpoint feature). For example, we could make data rate and disk usage be logging endpoints, and have set_condition be a triggerable response by the watchdog.

We could also consider if we want a #p8_alert to be sent at some less stringent set point. That would give the operator an opportunity to try and avoid the impending trip condition in a non-disruptive way.

**Comment by guiguem** [comment]
If such monitor is available and the dripline communication on firefly is set up, we could add a webpage for monitoring disks on the website:
https://github.com/project8/firefly/issues/1

**Comment by guiguem** [comment]
![img_0816](https://cloud.githubusercontent.com/assets/16764756/20683687/cd24544c-b561-11e6-825b-9ac0e2a4664c.jpg)
Here is a possible way to monitor the disks usage: a Go Disk Monitor program which sends alerts containing the disk usage from every DAQ machine (ignatius, zeppelin) and a dragonfly Space Manager service which collects these alerts and decides to do nothing, or to send a message in p8 alerts as a warning or send a set_condition to stop the DAQ and the execution script (need to be implemented).
I am thinking of a Go program, since dragonfly is not installed on these machines (and we might not want to) while Go is, and the disk monitor programs should be kind of "permanent" once implemented (just like hornet does not change a lot).
Comments?

**Comment by nsoblath** [comment]
We could easily put a Go program in Swarm to do this.  We could use the dungbeetle code with some simple replacements.

**Comment by guiguem** [comment]
Can dungbeetle send alerts?
Which program (hornet, dungbeetle etc) is the most close to sending alerts using dripline go?

**Comment by nsoblath** [comment]
Any of the programs can send alerts.

Dungbeetle already has the right program structure for what you want. At regular intervals it does something, and otherwise is available to receive and respond to dripline requests.

**Comment by guiguem** [comment]
The first part of the scheme is done by diopsid which is a Go program in swarm.
Sending alerts containing the all and used space on the `disk_status.name_of_machine` queue every minute (configurable).

**Comment by guiguem** [comment]
The reception of the alerts by disk_monitor has been implemented. The first version of this service (running on claude) will let the operator know (via logger.critical, transferred to slack via AMQPHandler and SlackInterface service) when the disk usage reaches a certain usage level (warning) and another (critical).
When the critical level is reached, a set_condition will be sent (once implemented).
The condition number will depend on the machine and disk at the origin of the critical and will be defined in the disk_monitor config file.
Before implementing this set_condition feature in disk_monitor, the set_condition needs to be defined in dripline and every relevant class of dragonfly.
Therefore I am not closing this issue which is then related to https://github.com/project8/dragonfly/issues/71 and https://github.com/project8/dripline/issues/163

**Comment by guiguem** [comment]
This issue has been solved with the pull request #82

**Comment by guiguem** [comment]
An extra feature is that, depending on the nature of the DAQ, we might want to set a different percent of free disk which will trigger a warning or crticical.
This will require minor adjustments in the DiskMonitor class.
