### ISSUE TITLE
T2 gas system

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#85]
Here is a placeholder for the work we need to do for having a working slow control for the T2 gas system.
Some details about the architecture can be found [here](https://basecamp.com/1780990/projects/338746/messages/65712758).
Some of the below items could be used as they are or implemented into a new RaspberryPiInterface class.

- Raspberry Pi:
  - Valves
    - [x] Implement the control of the valves with the Raspberry Pi
    - [x] Implement the reading of the valves status with the Raspberry Pi
  - Ion gauges
    - [x] ~~Interfaces with the RSA485 communication shield~~
- Temperature controller
  - [x] Create config file using EthernetProvider
- Leak valve
  - [x] Create config file using EthernetProvider
- RGA
  - [x] Possibly interface a gas composition scan start with dragonfly

**Comment by guiguem** [comment]
For the dragonfly integration of the RPi, the valves control and the IG reading, there are some scripts capable of doing such thing: 
- [ ] Integrate the control of the open pins into dragonfly: create a new RPiInterface class maybe which makes kind of a copy/paste of the python software: https://github.com/skiwithpete/relaypi/tree/master/8port
- [ ] Add set/get endpoints for the pressures read by the IG and the status of the valves

**Comment by wcpettus** [comment]
more basically, this will use the RPi.GPIO module:
https://sourceforge.net/p/raspberry-gpio-python/wiki/Home/

Examples there should provide more generic guidance on using the functionality

**Comment by wcpettus** [comment]
cooking-hacks has their example code in C, but LinkSprite used python, which should be easier.

Communication over the RS485 shield will require the serial package (from `pip install pyserial`):
https://www.raspberrypi.org/forums/viewtopic.php?f=91&t=158737
and some more helpful notes:
http://elinux.org/RPi_Serial_Connection#Connection_to_a_microcontroller_or_other_peripheral

**Comment by wcpettus** [comment]
Since the RS485 is all communicating over the same serial port off the RPi liz, we could use a repeater_provider-type service to handle all traffic, this will be some RPiSerialProvider instance.  Then the four instruments downstream (2x ion gauges, NEXTorr getter, and B-Rax) could be controlled with separate config files using an RS485Provider that inherits from RepeaterProvider, and normal(?) Spimes.

Alternatively, they can all be run in the same service like the muxer.

We should define what counts as an "instrument" and is named.  The muxer was one instrument controlling lots of sensors.  Is the RS485 shield the instrument? or are each of the ion gauges, etc their own instruments?

**Comment by wcpettus** [comment]
Some complications with the RS485 communication:
- the RPi shields appear to be a bust for RS485 communication (unclear why, it just doesn't work)
- the SAES NIOPS appears to use Modbus only, the others don't

So a revised plan for these instruments:
- get a new ethernet to RS485 adapter from Lantronix (ordered, available after collaboration meeting), use for Lesker and B-RAX
- run the SAES NIOPS on the existing RS232 adapter from Lantronix
- run the RGA directly from the serial port on dorian

**Comment by guiguem** [comment]
If this new plan is implemented, the communication will no longer use the LAN COM Port, which was the reason why the C# libraries from exTorr were not working correctly.
So if someone wants to refactor mosquito into a pure C# and dripline-C# interface, this will be possible.

**Comment by wcpettus** [comment]
update - the Instrutech B-RAX is communicating over RS-485, ion gauges will be tested once reconnected next week; SAES isn't communicating over RS-485 and I never heard back from their technicians, so I assume that will require RS-232

after connecting everything next week, I will start working on IEEE802 comm for the leak valve

**Comment by wcpettus** [comment]
The leak valve communication has been established using normal IEEE488 communication, so a special dragonfly provider is not required.
