### ISSUE TITLE
Integration of ROACH Interface in dragonfly

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#87]
Here are some features that one might want to have consistency between our two DAQ systems.
These items can be of course discussed and readjusted if necessary, but keeping in mind that consistency is the goal.
Some items might have already been completed.

- [x] All configurations of the DAQ should be done prior to starting the run/execution script.
This should be detailed in the wiki and can be as complex as necessary, even if a simple configuration using simple command is better.
The only last-second thing in the start_timed_run are getting the run number from the DB, defining the naming pattern and checking that everything is fine (_do_checks, is_running…).
- [x] A run should be started using x.start_timed_run
- [x] The roach interface should have a set_condition method and prevent new run to start when in safe mode
- [x] The roach interface should have a determine_RF_ROI method
- [x] The roach interface should have a is_running property returning True or false.
- [x] The roach interface should have a _do_checks method, which contains all the last minute check before starting the run.
- [x] is_running should return (something equivalent is fine) 0 when not running, 1 when running and 2 if in safe mode 
- [x] RSA and roach should have the same filename pattern
- [x] Parameters of the DAQ should be accessible via endpoints (central frequency, frequency span...)
- [x] Should include a self._path_separator ```\``` or ```/``` depending on the nature of the OS.

**Comment by laroque** [comment]
To clarify the third from last item, based on slack discussion, the "safe mode" checks should be done in the DAQ base class as part of start_run's implementation there. That way it is ensured that all systems behave in the same way.

Further discussion of "mode" values in the context of the dripline standard will need to be had.

Also, when in safe mode, we should signal that to other objects with a return code, not a payload value (unless the request was specifically a state query).

**Comment by guiguem** [comment]
Some updates about the items above:
- Following Slack discussion, the is_running will return true or false. 
If the DAQ is in safe mode when starting a new run, it will be stopped and raise an Exception DAQNotEnabled.
- Set_condition is now a DAQProvider method, which means that it is no longer required in the ROACHDAQInterface.
- The filename pattern is done in the base class in start_timed_run

**Comment by guiguem** [comment]
I discussed with Walter. he does not see a way to completely remove the set_central_frequency functions, but using property and xxx.setter in the ROACH2Interface,
```   
    @property
    def central_frequency(self):
         freq = artoodaq.xxx(blabla)
        return freq
    @central_frequency.setter
    def central_frequency(self, value):
         artoodaq.xxx(blabla,value)
```
and in the config file it will be something like:
 ```
endpoints:
  - name: roach_central_frequency
    module: ProviderAttributeSpime
    attribute_name: central_frequency
```

**Comment by guiguem** [comment]
Added the separator in the to-do list
