### ISSUE TITLE
Unnecessary packages

### ISSUE THREAD

**Issue by guiguem** [project8/dragonfly#92]
The installation of dragonfly and dripline are very long, mainly due to cython and numpy getting installed.
As a follow-up question, is there some packages that we don't longer need but which are installed anyway?

**Comment by laroque** [comment]
Cython is there because it makes the numpy (and especially scipy) installations much more reliable. The same may be true for other dependencies with C/C++ backends but I'm not sure which if any apply. I fully support purging dependencies we don't actually need.

**Comment by guiguem** [comment]
For some reasons, myrna always finishes before claude when installing. I suspect that Cython is somehow already installed on myrna, but not on claude.

**Comment by wcpettus** [comment]
Mathieu and I checked, numpy shouldn't be a dependency anymore (since it's purged from the ESR service now that analysis is separate).
Getting dragonfly working on the new RPi's is a good opportunity to check these dependencies, we can try sequentially removing them and seeing how it goes.

**Comment by wcpettus** [comment]
Cython has been listed as an "extras_require" for the database, but I test-installed on myrna and could run those services without cython.  The install is much faster as a result, and this dependency has been removed.

Using `pip install` handles the dependencies and versions much more cleanly than `python setup.py install`, so the documentation and install scripts have been updated to reflect this.

Resolution is staged in develop for the next dragonfly release (v1.5.5)
