### ISSUE TITLE
implement pinger endpoint

### ISSUE THREAD

**Issue by laroque** [project8/dragonfly#98]
The endpoint will, at some interval, ping all services in a configured list and ensure that each produces a reply. The endpoint will directly call its services on_alert_message method (it is expected that the Provider will be a SlackInterface, or equivalent if we add email/sms/etc. support). This will ensure that if AMQP communication is lost for some reason, notifications will be sent to users/operators in this way.

This is a consequence of removing the slack log handler from each service and placing it into a dedicated service, if a program crashes it may not be able to send an AMQP message to the slack service to trigger this message.

**Comment by guiguem** [comment]
We have that.
